export function useCard() {
    return [
    {
        id: 1,
        views: 750,
        daysAgo: 2,
        price: '450 500',
        title: 'Clavia Nord Grand сценическое цифровое пианино',
        image: '/img/piano.jpg',
        status: 'promoted',
    },
    {
        id: 2,
        views: 255,
        daysAgo: 4,
        price: '3 285 000',
        title: 'Hyundai Sonata 2.0 AT, 2023, 30 км',
        image: '/img/car.jpg',
        status: 'active',
    },
    {
        id: 3,
        views: 255,
        daysAgo: 2,
        price: '4 800 000',
        title: '2-к. квартира, 46 м², 1/5 эт.',
        image: '/img/apartment.jpg',
        status: 'active',
    },
    {
        id: 4,
        views: 255,
        daysAgo: 2,
        price: '7 500',
        priceType: 'шт',
        title: 'Старые барабаны',
        image: '/img/drums.jpg',
        status: 'active',
    },
    {
        id: 5,
        views: 255,
        daysAgo: 2,
        price: '7 500',
        title: 'DMX сплиттер RJ45 to 4x XLR Stairville',
        image: '/img/dmx.jpg',
        status: 'active',
    },
    {
        id: 6,
        views: 255,
        daysAgo: 2,
        price: '217 500',
        title: 'Мотоцикл honda',
        image: '/img/honda.jpg',
        status: 'active',
    },
    {
        id: 7,
        views: 255,
        daysAgo: 2,
        price: '17 900',
        title: 'Иж юпитер 5',
        image: '/img/bike.jpg',
        status: 'active',
    },
    {
        id: 8,
        views: 255,
        daysAgo: 2,
        price: '7 500',
        title: 'Пылесос кёрхер с водяным мешком для сбора пыли',
        image: '/img/cleaner.jpg',
        status: 'hidden',
    },
    ];
}